import { useCallback, useEffect, useMemo, useState } from 'react'
import { VirtualSolenoidActuator } from '../actuation/VirtualSolenoidActuator'
import { RuleBasedDecisionEngine } from '../decision/RuleBasedDecisionEngine'
import { ESP32HttpSensorProvider } from '../hardware/Esp32Adapter'
import { createInitialFarm, farmConfig, type Farm, type FarmEvent } from '../models/farm'
import { SimulatedCapacitiveMoistureSensorProvider, SimulatedEnvironmentProvider } from '../simulation/SensorSimulator'
const initialTime = new Date('2026-08-28T08:00:00')
const makeEvent = (message: string, kind: FarmEvent['kind'] = 'system', time = initialTime): FarmEvent => ({ id: crypto.randomUUID(), time: time.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), message, kind })
export function useFarmSimulation() {
  const engine = useMemo(() => new RuleBasedDecisionEngine(farmConfig.moistureThreshold), []); const sensorProvider = useMemo(() => new SimulatedCapacitiveMoistureSensorProvider(farmConfig.sensorNoiseLevel), []); const hardwareProvider = useMemo(() => new ESP32HttpSensorProvider(), []); const environment = useMemo(() => new SimulatedEnvironmentProvider(), []); const actuator = useMemo(() => new VirtualSolenoidActuator(engine, farmConfig.irrigationEffect, farmConfig.irrigationWaterLitres), [engine])
  const [farm, setFarm] = useState<Farm>(createInitialFarm); const [running, setRunning] = useState(false); const [autoMode, setAutoMode] = useState(false); const [dataSourceMode, setDataSourceMode] = useState<'simulation' | 'hardware'>('simulation'); const [demoPending, setDemoPending] = useState(false); const [speed, setSpeed] = useState(1); const [step, setStep] = useState(0); const [simulationTime, setSimulationTime] = useState(initialTime); const [events, setEvents] = useState<FarmEvent[]>([makeEvent('Digital farm initialized with 9 simulated capacitive moisture sensors.')])
  const finishIrrigation = useCallback((row: number, column: number, time: Date, source: 'manual' | 'auto') => { setFarm((previous) => { const result = actuator.irrigatePatch(previous, row, column, time); const sampled = sensorProvider.sampleFarm(result.farm, time, step + 1, `patch-${row}-${column}`); const patches = sampled.patches.map((patch) => ({ ...patch, irrigationRequired: engine.requiresIrrigation(patch) })); setEvents((log) => [result.events[2], ...log].slice(0, farmConfig.maxEvents)); return { ...sampled, patches, irrigationHistory: [...sampled.irrigationHistory, { timestamp: time.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), row, column, mode: source, waterUsed: farmConfig.irrigationWaterLitres }].slice(-farmConfig.maxIrrigationHistory) } }); }, [actuator, engine, sensorProvider, step])
  const irrigate = useCallback((row: number, column: number, source: 'manual' | 'auto' = 'manual') => { if (dataSourceMode === 'hardware') { hardwareProvider.irrigate({ patch: { row, column }, action: 'IRRIGATE' }).then((command) => setEvents((log) => [makeEvent(`Hardware irrigation command ${command.command_id} queued for Patch (${row},${column}); ${command.duration_ms} ms.`, 'action', simulationTime), ...log].slice(0, 60))).catch((error: Error) => setEvents((log) => [makeEvent(`Hardware irrigation blocked: ${error.message}`, 'warning', simulationTime), ...log].slice(0, 60))); return }; const target = farm.patches.find((patch) => patch.row === row && patch.column === column); const cooldown = target?.lastIrrigatedAt && simulationTime.getTime() - target.lastIrrigatedAt < farmConfig.irrigationCooldownMinutes * 60_000; if (!target || target.irrigationStatus === 'irrigating' || (source === 'auto' && cooldown)) return; setFarm((previous) => ({ ...previous, patches: previous.patches.map((patch) => patch.row === row && patch.column === column ? { ...patch, irrigationStatus: 'irrigating' } : patch) })); setEvents((log) => [makeEvent(`${source === 'auto' ? 'AUTO: ' : ''}Virtual solenoid activated for Patch (${row},${column}).`, 'action', simulationTime), makeEvent(`${source === 'auto' ? 'AUTO: ' : ''}Irrigation requested for Patch (${row},${column}).`, 'action', simulationTime), ...log].slice(0, 60)); window.setTimeout(() => finishIrrigation(row, column, simulationTime, source), farmConfig.irrigationDurationMs) }, [dataSourceMode, farm.patches, finishIrrigation, hardwareProvider, simulationTime])
  const advance = useCallback(() => { const nextTime = new Date(simulationTime.getTime() + farmConfig.simulationStepMinutes * 60_000); const nextStep = step + 1; setStep(nextStep); setSimulationTime(nextTime); if (dataSourceMode === 'hardware') return; setFarm((previous) => { const environmentFarm = { ...previous, patches: previous.patches.map((patch) => environment.advance(patch, nextStep)) }; const sampled = sensorProvider.sampleFarm(environmentFarm, nextTime, nextStep); const patches = sampled.patches.map((patch) => ({ ...patch, irrigationRequired: engine.requiresIrrigation(patch) })); const newlyDry = patches.filter((patch, index) => patch.irrigationRequired && !previous.patches[index].irrigationRequired); setEvents((log) => [makeEvent('Sensor sample received: 9 moisture readings updated.', 'system', nextTime), ...newlyDry.map((patch) => makeEvent(`Sensor ${patch.sensorId}: Patch (${patch.row},${patch.column}) fell below threshold; irrigation required.`, 'warning', nextTime)), ...log].slice(0, farmConfig.maxEvents)); if (autoMode) window.setTimeout(() => patches.filter((patch) => patch.irrigationRequired && patch.irrigationStatus === 'idle' && (!patch.lastIrrigatedAt || nextTime.getTime() - patch.lastIrrigatedAt >= farmConfig.irrigationCooldownMinutes * 60_000)).forEach((patch) => irrigate(patch.row, patch.column, 'auto')), 0); return { ...sampled, patches } }) }, [autoMode, dataSourceMode, engine, environment, irrigate, sensorProvider, simulationTime, step])
  useEffect(() => { if (!running) return; const timer = window.setInterval(advance, 1600 / speed); return () => window.clearInterval(timer) }, [advance, running, speed])
  useEffect(() => {
    if (dataSourceMode !== 'hardware') return
    hardwareProvider.readSensors().then(({ sensors, environment }) => {
      setFarm((previous) => ({
        ...previous,
        patches: previous.patches.map((patch) => {
          const reading = sensors.find((sensor) => sensor.id === patch.sensorId)
          return reading?.moisture === null || !reading ? { ...patch, soilMoisture: Number.NaN, temperature: Number.NaN, humidity: Number.NaN, irrigationRequired: false, dataSource: 'measured' } : { ...patch, soilMoisture: reading.moisture, actualMoisture: reading.moisture, temperature: environment?.temperature ?? Number.NaN, humidity: environment?.humidity ?? Number.NaN, irrigationRequired: engine.requiresIrrigation({ ...patch, soilMoisture: reading.moisture }), dataSource: 'measured' }
        }),
        sensors: previous.sensors.map((sensor) => {
          const reading = sensors.find((item) => item.id === sensor.id)
          return !reading ? { ...sensor, currentReading: Number.NaN, status: 'offline', dataSource: 'measured' as const } : { ...sensor, currentReading: reading.moisture ?? Number.NaN, lastReading: reading.timestamp ?? 'unavailable', lastSampleAt: reading.timestamp ? new Date(reading.timestamp).getTime() : 0, status: reading.status === 'valid' ? 'active' : 'offline', dataSource: 'measured' as const }
        })
      }))
      setEvents((log) => [makeEvent(`Backend sensor refresh received: ${sensors.filter((sensor) => sensor.status === 'valid').length}/9 valid calibrated readings.`, 'system', new Date()), ...log].slice(0, 60))
      hardwareProvider.readCommandHistory().then((commands) => setEvents((log) => [...commands.map((command) => makeEvent(`Backend command ${command.id.slice(0, 8)}: Patch (${command.row},${command.column_number}) ${command.status}${command.error ? ` — ${command.error}` : ''}.`, command.status === 'failed' ? 'warning' : 'action', new Date(command.created_at))), ...log].slice(0, 60))).catch(() => undefined)
    }).catch((error: Error) => setEvents((log) => [makeEvent(`Backend unavailable: ${error.message}`, 'warning', simulationTime), ...log].slice(0, 60)))
  }, [dataSourceMode, engine, hardwareProvider, simulationTime])
  useEffect(() => { if (!demoPending || dataSourceMode !== 'simulation' || !autoMode) return; const center = farm.patches.find((patch) => patch.row === 1 && patch.column === 1); if (center && center.irrigationStatus === 'idle' && engine.requiresIrrigation(center)) { setDemoPending(false); irrigate(1, 1) } }, [autoMode, dataSourceMode, demoPending, engine, farm.patches, irrigate])
  const setSensorMoisture = (sensorId: string, moisture: number) => { if (dataSourceMode === 'hardware') { setEvents((log) => [makeEvent(`Manual simulated sensor test is unavailable while ESP32 hardware mode is selected.`, 'warning', simulationTime), ...log].slice(0, 60)); return false }; if (!Number.isFinite(moisture) || moisture < 0 || moisture > 100) return false; setFarm((previous) => { const updated = sensorProvider.setReading(previous, sensorId, moisture, simulationTime); const patches = updated.patches.map((patch) => ({ ...patch, irrigationRequired: engine.requiresIrrigation(patch) })); return { ...updated, patches } }); setEvents((log) => [makeEvent(`Manual sensor test: ${sensorId} set to ${moisture.toFixed(1)}%.`, 'system', simulationTime), ...log].slice(0, 60)); return true }
  const changeDataSource = (mode: 'simulation' | 'hardware') => { setDataSourceMode(mode); setEvents((log) => [makeEvent(mode === 'hardware' ? 'Hardware mode selected: ESP32 disconnected; simulation data preserved.' : 'Simulation mode selected: virtual sensors and actuator active.'), ...log].slice(0, 60)) }
  const runDemo = () => { if (dataSourceMode === 'hardware') { setEvents((log) => [makeEvent('Demo scenario requires Simulation data source; hardware mode is disconnected.', 'warning', simulationTime), ...log].slice(0, farmConfig.maxEvents)); return }; const previousAuto = autoMode; setAutoMode(true); setSensorMoisture('S11', 12); setDemoPending(true); setEvents((log) => [makeEvent('Demo scenario: S11 set dry; awaiting rule-based AUTO irrigation.', 'system', simulationTime), ...log].slice(0, farmConfig.maxEvents)); window.setTimeout(() => setAutoMode(previousAuto), farmConfig.irrigationDurationMs + 850) }
  const reset = () => { setFarm(createInitialFarm()); setRunning(false); setAutoMode(false); setDataSourceMode('simulation'); setDemoPending(false); setStep(0); setSimulationTime(initialTime); setEvents([makeEvent('Simulation reset: 9 simulated sensors restored to initial state.')]) }
  return { farm, running, setRunning, autoMode, setAutoMode, dataSourceMode, setDataSourceMode: changeDataSource, hardwareStatus: hardwareProvider.getStatus(), speed, setSpeed, simulationTime, events, irrigate, setSensorMoisture, runDemo, reset }
}
