export type DataSource = 'simulated' | 'measured' | 'estimated'
export type IrrigationStatus = 'idle' | 'irrigating'
export type SensorStatus = 'active' | 'offline'
export type SensorHealth = 'healthy' | 'warning' | 'offline'
export interface MoistureHistoryPoint { time: string; moisture: number; irrigated?: boolean }
export interface MoistureSensor { id: string; type: 'Capacitive Soil Moisture'; row: number; column: number; currentReading: number; lastReading: string; lastSampleAt: number; status: SensorStatus; dataSource: 'simulated' }
export interface Patch { id: string; row: number; column: number; sensorId: string; soilMoisture: number; actualMoisture: number; temperature: number; humidity: number; irrigationRequired: boolean; irrigationStatus: IrrigationStatus; lastIrrigated: string | null; lastIrrigatedAt: number | null; cumulativeWaterUsed: number; dataSource: DataSource; history: MoistureHistoryPoint[] }
export interface IrrigationHistory { timestamp: string; row: number; column: number; mode: 'manual' | 'auto'; waterUsed: number }
export interface Farm { patches: Patch[]; sensors: MoistureSensor[]; irrigationHistory: IrrigationHistory[] }
export interface FarmEvent { id: string; time: string; message: string; kind: 'system' | 'warning' | 'action'; type?: string }
export const farmConfig = { moistureThreshold: 30, evaporationRate: 0.42, sensorNoiseLevel: 0.7, sensorSamplingIntervalMinutes: 5, maxHistoryPoints: 160, maxEvents: 100, maxIrrigationHistory: 100, sensorWarningAgeMinutes: 15, sensorOfflineAgeMinutes: 30, irrigationEffect: 18, irrigationWaterLitres: 1.5, irrigationDurationMs: 650, irrigationCooldownMinutes: 20, simulationStepMinutes: 5 } as const
const seed = [[55, 26.4, 71], [42, 29.1, 62], [61, 24.8, 78], [35, 31.6, 53], [18, 33.4, 45], [48, 27.7, 66], [57, 25.5, 75], [31, 30.2, 58], [22, 34.1, 41]]
const at = (date: Date) => date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
export function createInitialFarm(): Farm { const start = new Date('2026-08-28T08:00:00'); const time = at(start); const patches = seed.map(([moisture, temperature, humidity], index) => { const row = Math.floor(index / 3); const column = index % 3; const sensorId = `S${row}${column}`; return { id: `patch-${row}-${column}`, row, column, sensorId, soilMoisture: moisture, actualMoisture: moisture, temperature, humidity, irrigationRequired: moisture < farmConfig.moistureThreshold, irrigationStatus: 'idle' as IrrigationStatus, lastIrrigated: null, lastIrrigatedAt: null, cumulativeWaterUsed: 0, dataSource: 'simulated' as DataSource, history: [{ time, moisture }] } }); return { patches, sensors: patches.map((patch) => ({ id: patch.sensorId, type: 'Capacitive Soil Moisture' as const, row: patch.row, column: patch.column, currentReading: patch.soilMoisture, lastReading: time, lastSampleAt: start.getTime(), status: 'active' as SensorStatus, dataSource: 'simulated' as const })), irrigationHistory: [] } }
