import { useState } from 'react'
import { ActivityLog } from './components/ActivityLog'
import { Dashboard } from './components/Dashboard'
import { FarmGrid } from './components/FarmGrid'
import { HardwareStatus } from './components/HardwareStatus'
import { PatchDetails } from './components/PatchDetails'
import { farmConfig, type Patch } from './models/farm'
import { useFarmSimulation } from './state/useFarmSimulation'
export default function App() { const simulation = useFarmSimulation(); const [selectedId, setSelectedId] = useState<string | null>('patch-1-1'); const selected = simulation.farm.patches.find((patch) => patch.id === selectedId) ?? null; const select = (patch: Patch) => setSelectedId(patch.id); const sensor = selected ? simulation.farm.sensors.find((item) => item.id === selected.sensorId) ?? null : null; const hardware = simulation.dataSourceMode === 'hardware'; return <main><header><div className="brand"><span className="mark">▦</span><div><p>PRECISION AGRICULTURE RESEARCH</p><h1>Digital Farm <em>03</em></h1></div></div><div className="simulated"><span /> {hardware ? 'Hardware mode — disconnected safe' : 'Simulated prototype data'}</div></header><section className="control-bar"><div><p className="eyebrow">FARM CLOCK</p><strong>{simulation.simulationTime.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} · {simulation.simulationTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</strong></div><div className="controls"><button onClick={() => simulation.setRunning(!simulation.running)} className={simulation.running ? 'pause' : 'start'}>{simulation.running ? 'Pause' : 'Start'}</button><button className={simulation.autoMode ? 'mode active-mode' : 'mode'} onClick={() => simulation.setAutoMode(!simulation.autoMode)}>Mode: {simulation.autoMode ? 'Auto' : 'Manual'}</button><div className="source-control"><span>Data</span><button className={!hardware ? 'active' : ''} onClick={() => simulation.setDataSourceMode('simulation')}>Simulation</button><button className={hardware ? 'active' : ''} onClick={() => simulation.setDataSourceMode('hardware')}>Hardware</button></div><button className="reset" onClick={simulation.reset}>Reset</button><div className="speed">{[1, 2, 5].map((value) => <button key={value} className={simulation.speed === value ? 'active' : ''} onClick={() => simulation.setSpeed(value)}>{value}×</button>)}</div></div></section><Dashboard farm={simulation.farm}/><HardwareStatus mode={simulation.dataSourceMode} status={simulation.hardwareStatus} sensorIds={simulation.farm.sensors.map((item) => item.id)}/><section className="workspace"><FarmGrid patches={simulation.farm.patches} selectedId={selectedId} onSelect={select}/><PatchDetails patch={selected} sensor={sensor} dataSourceLabel={hardware ? 'ESP32 Hardware (disconnected)' : 'Simulation'} onIrrigate={() => selected && simulation.irrigate(selected.row, selected.column)} onSetMoisture={(value) => selected ? simulation.setSensorMoisture(selected.sensorId, value) : false}/></section><ActivityLog events={simulation.events}/><footer><span>Prof. Lalit Kumar · University Precision Agriculture Project</span><span>Sensor sampling {farmConfig.sensorSamplingIntervalMinutes} min · threshold {farmConfig.moistureThreshold}% · cooldown {farmConfig.irrigationCooldownMinutes} min</span></footer></main> }
